### PR TITLE
Use phoneme lengths to trim samples

### PR DESCRIPTION
**Pull request by kahrendt**
- Trim the samples using phoneme lengths
  - Fixes bug where ``min-phoneme-count`` with a batch size larger than 1 producing not properly aligned samples
- Changed resampling method name to avoid a depreciation warning

### CODE REVIEW

**Comment by synesthesiam** [comment]
webrtcvad is being used to trim excess silence from all clips, not just the ones with repeated phrases to match the minimum phoneme count.
We can't just trim zeros, as there is some minor noise added by the underlying Piper models.

**Comment by kahrendt** [comment]
In my testing, it still worked fine without the minimum phoneme count set, but I will experiment some more. Is the minor noise you mention in the middle of the phrase? The PR will always remove silence at the end along and at the start only if the minimum phoneme count is set.

I'll try adding it back in and see if I can notice a difference in the quality.

**Comment by kahrendt** [comment]
I reverted removing webrtcvad. You are correct, it still does trim out a small amount of audio even after trimming 0s. It's a very small amount in terms of the raw audio length, so I didn't notice when just listening to the samples.

This PR still fixes the non-aligned samples with using the ``--min-phoneme-count`` and removes the depreciation warning.

**Comment by synesthesiam** [comment]
Great, thanks!

**Pull request merged**
